[package]
name = "paqjs"
version = "2.0.0"
authors = ["Gregory Langlais <_@gregorylanglais.com>"]
edition = "2021"
description = "Hash directory or file with BLAKE3."
license = "MIT"
readme = "README.md"
keywords = [
    "hash",
    "blake3",
    "directory-traversal",
    "cryptographic",
    "nodejs",
]
repository = "https://github.com/gregl83/paqjs"
homepage = "https://www.npmjs.com/package/@paqjs/core"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.12.2", default-features = false, features = ["napi4"] }
napi-derive = "3.6.3"
paq = "~2.0.0"

[build-dependencies]
napi-build = "2.4.1"
